version: "3"
services:
  master:
    image: arungupta/couchbase
    deploy:
      replicas: 1
    ports:
      - 8091:8091
    environment:
      TYPE: "MASTER"
    networks:
      - couchbase
networks:
  couchbase:
    driver: overlay